swagger: "2.0"
info:
  description: "API to manage Healthymood resources"
  version: "1.0.0"
  title: "Healthymood API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "ingredient"
  description: "operations on ingredients"
paths:
  /ingredients:
    get:
      tags:
      - "ingredient"
      summary: "Get a list of ingredients"
      description: ""
      responses:
        "200":
          description: "Everything went well"
          schema:
            type: 'object'
            properties:
              data:
                type: 'array'
                items: 
                  $ref: '#/definitions/IngredientSimplified'
    post:
      tags:
      - "ingredient"
      summary: "Add a new ingredient"
      description: ""
      parameters:
      - in: "body"
        name: "ingredient"
        description: "Ingredient object that needs to be added in DB"
        required: true
        schema:
          allOf:
           - $ref: "#/definitions/IngredientEditableAttributes"
           - type: 'object'
             required:
              - "name"
      responses:
        "201":
          description: "Created"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Ingredient"
        "400":
          description: "Invalid input. The ingredient object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
          
  /ingredients/{ingredientId}:
    get:
      tags:
      - "ingredient"
      summary: "Find a ingredient by ID"
      description: "Returns a single ingredient"
      parameters:
      - name: "ingredientId"
        in: "path"
        description: "ID of ingredient to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: 'object'
            properties:
              data:
                type: "object"
                $ref: "#/definitions/Ingredient"
        "404":
          description: "ingredient not found"
    put:
      tags:
      - "ingredient"
      summary: "Update an existing ingredient"
      description: ""
      parameters:
      - name: "ingredientId"
        in: "path"
        description: "ID of ingredient to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "ingredient"
        description: "ingredient object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/IngredientEditableAttributes"
      responses:
        "200":
          description: "Updated"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Ingredient"
        "404":
          description: "ingredient not found"
        "400":
          description: "Invalid input. The ingredient object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
    delete:
      tags:
      - "ingredient"
      summary: "Deletes an ingredient"
      description: ""
      parameters:
      - name: "ingredientId"
        in: "path"
        description: "ingredient id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "ingredient not found"
        "200":
          description: "OK"
definitions:
  IngredientEditableAttributes:
    type: "object"
    properties:
      name:
        type: "string"
        example: "cucumber"
      is_allergen:
        type: "boolean"
        example: false
      
  IngredientSimplified:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "cucumber"
      is_allergen:
        type: "boolean"
        example: false
      
  Ingredient:
    allOf: 
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: '#/definitions/IngredientEditableAttributes'
